document.getElementById("boardArtImg").src="data:image/webp;base64,"+(window.__BOARD_B64||"");
const ATLAS_URL="data:image/avif;base64,"+(window.__ATLAS_B64||"");const ATLAS_COLS=8,ATLAS_ROWS=6;const CHARACTERS=[{"category":"LORD","name":"PLUME BLIZZARD","i":0},{"category":"COMMON","name":"DYNAMITER","i":1},{"category":"ELITE","name":"ARCHER","i":2},{"category":"RARE","name":"ALAT DENYUT","i":3},{"category":"LEGENDARY","name":"DESTRUCTIVE DEVICE","i":4},{"category":"MYTHIC","name":"SHADOW HUNTER","i":5},{"category":"IMMORTAL","name":"IGNIS","i":6},{"category":"COMMON","name":"WARRIOR","i":7},{"category":"ELITE","name":"FLOATING CANNON","i":8},{"category":"RARE","name":"ALAT DENYUT X3","i":9},{"category":"LEGENDARY","name":"BULLHEAD WARRIOR","i":10},{"category":"MYTHIC","name":"BLACK TORTOISE","i":11},{"category":"IMMORTAL","name":"CHANG'E","i":12},{"category":"COMMON","name":"ELEMENT ELF","i":13},{"category":"ELITE","name":"CRUSADERS","i":14},{"category":"RARE","name":"PERFORMER","i":15},{"category":"LEGENDARY","name":"BULLHEAD WARRIOR X3","i":16},{"category":"MYTHIC","name":"VOODOO RITUAL","i":17},{"category":"IMMORTAL","name":"ARES","i":18},{"category":"COMMON","name":"HUNTER","i":19},{"category":"ELITE","name":"SISTER","i":20},{"category":"RARE","name":"MUSKETEER","i":21},{"category":"LEGENDARY","name":"STORM MAGIC MENTOR","i":22},{"category":"MYTHIC","name":"GRIFFIN","i":23},{"category":"COMMON","name":"RANGER","i":24},{"category":"ELITE","name":"GHOST WARRIOR","i":25},{"category":"RARE","name":"SCREECH-OWL PITCHER","i":26},{"category":"LEGENDARY","name":"CHRONO ARTILLERIST","i":27},{"category":"MYTHIC","name":"FROZEN HEART","i":28},{"category":"RARE","name":"SCREECH-OWL PITCHER X3","i":29},{"category":"MYTHIC","name":"TERMINATOR","i":30},{"category":"RARE","name":"GREATSWORD PENGUIN","i":31},{"category":"MYTHIC","name":"SCARLET SCYTHE","i":32},{"category":"RARE","name":"GREATSWORD PENGUIN X3","i":33},{"category":"MYTHIC","name":"NECROMANCY WITCH","i":34},{"category":"MYTHIC","name":"FLASH","i":35},{"category":"MYTHIC","name":"SHIMMER","i":36},{"category":"MYTHIC","name":"SUN WUKONG","i":37},{"category":"MYTHIC","name":"EVIL CHANTER","i":38},{"category":"MYTHIC","name":"FLAMMING DRAGON","i":39},{"category":"MYTHIC","name":"CROCODILE BULLY","i":40},{"category":"MYTHIC","name":"SWORD SPIRIT","i":41},{"category":"MYTHIC","name":"COIN-OP MACHINE","i":42},{"category":"MYTHIC","name":"HOLY ENVOY","i":43},{"category":"MYTHIC","name":"BLAST CAT","i":44},{"category":"MYTHIC","name":"JADEWARE","i":45}];
const CATEGORIES=['LORD','COMMON','ELITE','RARE','LEGENDARY','MYTHIC','IMMORTAL'],STORAGE_KEY='toonBoardFormation_v1';
const playable=[];for(let r=2;r<=4;r++)for(let c=2;c<=7;c++)playable.push(String.fromCharCode(64+c)+r);
let state={},activeCell=null,activeCategory='LORD',dialogMode='share',forcedBoardRotation=false;
const grid=document.getElementById('grid'),sheet=document.getElementById('sheet'),backdrop=document.getElementById('backdrop'),cats=document.getElementById('cats'),toonGrid=document.getElementById('toonGrid'),saveState=document.getElementById('saveState');
function loadState(){try{state=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{}}catch{state={}}}
function saveStateNow(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));saveState.textContent='Saved on this device';setTimeout(()=>saveState.textContent='Saved',900)}
function assetFor(n){return CHARACTERS.find(x=>x.name===n)}
function spriteStyle(ch){const c=ch.i%ATLAS_COLS,r=Math.floor(ch.i/ATLAS_COLS),x=c*100/(ATLAS_COLS-1),y=r*100/(ATLAS_ROWS-1);return `background-image:url("${ATLAS_URL}");background-size:${ATLAS_COLS*100}% ${ATLAS_ROWS*100}%;background-position:${x}% ${y}%;background-repeat:no-repeat`}
function makeGrid(){grid.innerHTML='';for(let r=1;r<=5;r++)for(let c=1;c<=8;c++){const id=String.fromCharCode(64+c)+r;if(playable.includes(id)){const b=document.createElement('button');b.className='cell playable';b.dataset.cell=id;b.type='button';b.setAttribute('aria-label',`Board square ${id}`);b.onclick=()=>openPicker(id);grid.appendChild(b)}else{const d=document.createElement('div');d.className='cell-spacer';d.dataset.cell=id;grid.appendChild(d)}}renderBoard()}
function renderBoard(){document.querySelectorAll('.cell.playable').forEach(cell=>{cell.querySelectorAll('.toonSprite').forEach(n=>n.remove());const ch=assetFor(state[cell.dataset.cell]);if(ch){const d=document.createElement('div');d.className='toonSprite';d.style.cssText=spriteStyle(ch);cell.appendChild(d)}})}
function renderCats(){cats.innerHTML='';CATEGORIES.forEach(cat=>{const b=document.createElement('button');b.className='cat'+(cat===activeCategory?' active':'');b.textContent=cat;b.onclick=()=>{activeCategory=cat;renderCats();renderToons()};cats.appendChild(b)})}
function renderToons(){toonGrid.innerHTML='';CHARACTERS.filter(x=>x.category===activeCategory).forEach(ch=>{const b=document.createElement('button');b.className='toon-card';const d=document.createElement('div');d.className='pickSprite';d.style.cssText=spriteStyle(ch);const s=document.createElement('span');s.textContent=ch.name;b.append(d,s);b.onclick=()=>placeToon(ch.name);toonGrid.appendChild(b)})}
function openPicker(id){activeCell=id;document.querySelectorAll('.cell.playable').forEach(x=>x.classList.toggle('selected',x.dataset.cell===id));document.getElementById('sheetTitle').textContent=`Square ${id}`;const cur=state[id];document.getElementById('sheetSub').textContent=cur?`Current: ${cur}`:'Empty square';if(cur){const ch=assetFor(cur);if(ch)activeCategory=ch.category}renderCats();renderToons();sheet.classList.add('open');backdrop.classList.add('open')}
function closePicker(){sheet.classList.remove('open');backdrop.classList.remove('open');document.querySelectorAll('.cell.playable').forEach(x=>x.classList.remove('selected'));activeCell=null}
function placeToon(name){if(!activeCell)return;state[activeCell]=name;renderBoard();saveStateNow();toast(`${name} placed in ${activeCell}`);closePicker()}
function removeToon(){if(!activeCell)return;delete state[activeCell];renderBoard();saveStateNow();toast(`${activeCell} cleared`);closePicker()}
function encodeState(){const clean={};playable.forEach(k=>{if(state[k])clean[k]=state[k]});return btoa(unescape(encodeURIComponent(JSON.stringify(clean))))}
function decodeState(code){return JSON.parse(decodeURIComponent(escape(atob(code.trim()))))}
function showDialog(mode){dialogMode=mode;const dlg=document.getElementById('codeDialog'),box=document.getElementById('codeBox'),title=document.getElementById('dialogTitle'),text=document.getElementById('dialogText'),action=document.getElementById('copyOrLoadBtn');document.getElementById('dialogBackdrop').classList.add('open');dlg.classList.add('open');if(mode==='share'){title.textContent='Share Board';text.textContent='Copy this code and send it through Discord.';box.value=encodeState();box.readOnly=true;action.textContent='Copy Code'}else{title.textContent='Load Board';text.textContent='Paste a Toon Board code below.';box.value='';box.readOnly=false;action.textContent='Load Board'}}
function closeDialog(){document.getElementById('dialogBackdrop').classList.remove('open');document.getElementById('codeDialog').classList.remove('open')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),1500)}
function viewportSize(){const vv=window.visualViewport;return{w:Math.max(1,Math.round(vv?vv.width:innerWidth)),h:Math.max(1,Math.round(vv?vv.height:innerHeight))}}
function sizeFullBoard(){if(!document.body.classList.contains('full-board'))return;const board=document.getElementById('board'),{w,h}=viewportSize(),ratio=984/535,browserIsLandscape=w>h,rotateInside=forcedBoardRotation&&!browserIsLandscape;document.body.classList.toggle('force-rotate',rotateInside);let bw,bh;if(rotateInside){bw=Math.min(h,w*ratio);bh=bw/ratio}else{bw=Math.min(w,h*ratio);bh=bw/ratio}board.style.width=`${bw}px`;board.style.height=`${bh}px`;board.style.aspectRatio='auto'}
async function setFullBoard(on){document.body.classList.toggle('full-board',!!on);document.getElementById('fullBtn').textContent=on?'Normal View':'Large Board';if(on){try{if(document.documentElement.requestFullscreen&&!document.fullscreenElement)await document.documentElement.requestFullscreen()}catch{}try{if(screen.orientation?.lock)await screen.orientation.lock('landscape')}catch{}setTimeout(sizeFullBoard,30)}else{forcedBoardRotation=false;document.body.classList.remove('force-rotate');document.getElementById('fullRotate').textContent='Rotate View';const b=document.getElementById('board');b.style.width='';b.style.height='';b.style.aspectRatio='';b.style.transform='';try{if(document.fullscreenElement&&document.exitFullscreen)await document.exitFullscreen()}catch{}try{screen.orientation?.unlock?.()}catch{}}setTimeout(()=>scrollTo(0,0),30)}
function toggleForcedRotation(){forcedBoardRotation=!forcedBoardRotation;document.getElementById('fullRotate').textContent=forcedBoardRotation?'Normal View':'Rotate View';sizeFullBoard();setTimeout(()=>scrollTo(0,0),20)}
function handleViewportChange(){if(document.body.classList.contains('full-board'))sizeFullBoard();setTimeout(()=>scrollTo(0,0),20)}
addEventListener('resize',handleViewportChange,{passive:true});addEventListener('orientationchange',()=>setTimeout(handleViewportChange,120),{passive:true});visualViewport?.addEventListener('resize',handleViewportChange,{passive:true});
function init(){loadState();makeGrid();document.getElementById('artBtn').onclick=()=>toast('All artwork is built into this version')}
init();backdrop.onclick=closePicker;document.getElementById('closeSheet').onclick=closePicker;document.getElementById('cancelBtn').onclick=closePicker;document.getElementById('removeBtn').onclick=removeToon;document.getElementById('resetBtn').onclick=()=>{if(confirm('Clear every toon from the board?')){state={};renderBoard();saveStateNow();toast('Board reset')}};document.getElementById('fullBtn').onclick=()=>setFullBoard(!document.body.classList.contains('full-board'));document.getElementById('fullExit').onclick=()=>setFullBoard(false);document.getElementById('fullRotate').onclick=toggleForcedRotation;document.getElementById('shareBtn').onclick=()=>showDialog('share');document.getElementById('loadBtn').onclick=()=>showDialog('load');document.getElementById('closeDialog').onclick=closeDialog;document.getElementById('dialogBackdrop').onclick=closeDialog;document.getElementById('copyOrLoadBtn').onclick=async()=>{const box=document.getElementById('codeBox');if(dialogMode==='share'){try{await navigator.clipboard.writeText(box.value);toast('Board code copied')}catch{box.select();document.execCommand('copy');toast('Board code copied')}}else{try{const loaded=decodeState(box.value),valid={};for(const[k,v]of Object.entries(loaded))if(playable.includes(k)&&assetFor(v))valid[k]=v;state=valid;renderBoard();saveStateNow();closeDialog();toast('Board loaded')}catch{toast('That board code is not valid')}}};